Pandas Lab 1

For this lab, you will need to read in the provided FASTA file and generate a DataFrame containing the following information for each sequence record:

    Sequence Length
    GC content
    Begins with start codon?
    Ends in stop codon?
    Complete frame? (Meaning is the length a multiple of 3?)

The row index should be the sequence label, and columns should be labeled with descriptions of these 5 criteria I've given you. Be mindful of the datatype you choose for description 3-5.

In [84]:

from Bio import SeqIO
import pandas as pd

starts = ""
stops = ""
completes = ""
seq_id =[]
seq_length = []
gcp = []
start = []
stop = []
complete= []

# parse through fasta file and append lists for each required attribute
for record in SeqIO.parse('Mdomestica-pandasLab.fa','fasta'):
    
    
    lengths = str(len(record.seq))
    gc = str((record.seq.count('G') + record.seq.count('C')) / len(record.seq))
    #print(gc)
    if record.seq.startswith("ATG"): 
        starts = "TRUE"
    else: 
        starts = "FALSE"
    if record.seq.endswith("TAA") or record.seq.endswith("TAG") or record.seq.endswith("TGA"):
        stops = "TRUE"
    else:
        stops = "FALSE"
    if len(record.seq) % 3 == 0:
        completes = "TRUE"
    else:
        completes = "FALSE"
        
    # create lists for record id to be used as row values
    seq_id.append(record.id)
    
    # append the results from for loop into 5 lists that will become columns and values 
    # sequence length | gc content | start, stop codons | complete frame columns
    seq_length.append(lengths)
    gcp.append(gc)
    start.append(starts)
    stop.append(stops)
    complete.append(completes)
 
 # provide column names to match with the list of values     
data = {'Sequence Length' : seq_length,
        'GC Content' : gcp,
        'Start Codon' : start,
        'Stop Codon' : stop,
        'Complete Frame' : complete}   

# create row names to match the sequence ids 
read_table = pd.DataFrame(data, index=seq_id)

    
read_table

,Sequence Length,GC Content,Start Codon,Stop Codon,Complete Frame
MD10G1276500,2940,0.4605442176870748,FALSE,TRUE,TRUE
MD10G1110200,1731,0.464471403812825,TRUE,TRUE,TRUE
MD10G1036500,468,0.5448717948717948,TRUE,TRUE,TRUE
MD10G1170700,1728,0.44675925925925924,TRUE,TRUE,TRUE
MD10G1250900,1278,0.4029733959311424,TRUE,TRUE,TRUE
...,...,...,...,...,...
MD14G1066400,423,0.5295508274231678,TRUE,TRUE,TRUE
MD14G1225900,594,0.5033670033670034,TRUE,TRUE,TRUE
MD14G1120900,939,0.48136315228966986,TRUE,TRUE,TRUE
MD14G1057700,483,0.5238095238095238,TRUE,TRUE,TRUE
MD14G1237500,3270,0.44220183486238535,TRUE,TRUE,TRUE